### ISSUE TITLE
"build-web" places resulting script in root directory

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#162]
The current "build-web" script places the `GridEngine.min.js` file into the root project directory, not `dist/`. Because of this, you can't import the non-ESM build easily into any other projects. 

Easy fix; just add `dist/` to the `--outfile` argument for "build-web"

**Comment by Annoraaq** [comment]
Hey @splashsky

This is intentional. The reason for it not being in dist is that it is not supposed to be exported as an npm module. The non-esm version is intended for manual download only. Putting it in the dist directory would make the npm package twice as large.
Unfortunately I could not find a way to exclude single files from being published to npm.

> Because of this, you can't import the non-ESM build easily into any other projects.

Could you be more specific about this case? I think I don't understand the issue.

**Comment by splashsky** [comment]
In my use case, I was trying to make a script that would contain accessible instances of both Phaser and Grid Engine. However, they wouldn't be in the global namespace as ESM modules so that was out of the question. I then set up a simple script to copy the minified scripts from `node_modules`, which worked for Phaser but not for Grid Engine, because Grid Engine's minified universal script wasn't there.

While I understand wanting to save the Mb, would it be alright for the sake of convenience to simply let the universal script exist there? Phaser does it, and those versions are each ~3Mb. Realistically, letting another +/- 48Kb  be downloaded seems trivial at worst, convenient at best.

**Comment by Annoraaq** [comment]
I merged it. It will be part of the next release.
