### ISSUE TITLE
example code for detecting arriving at destination

### ISSUE THREAD

**Issue by gureckis** [Annoraaq/grid-engine#166]
Hi,
Thanks for a great package, it is so well documented and really helping me on a project.  One issue is that I want some code to execute when my character moves to a particular location using `.moveTo()`, specifically when it arrives at the final destination.  I looked at the closed issues and discussions a lot to see the recommendation to use either `getPosition()` or `positionChangeFinished()` but these seem a bit obtuse.  `positionChangeFinished()` notifies about every tile change so it will fire too often.  And `getPosition()` requires checking each location over and over in the loop.  It seems like at the end of the `moveTo()` methods there should be some type of observable issued that is like "I went to where you told me to go" or "I couldn't go there" so you can handle the end of the route planning.  

I might be thinking about this wrong?  

In either case, perhaps an example for this could be added to the docs underneath the **MoveTo** example.  If I got a hint I could try a PR but I feel my current hack (which works) is not that nice:

```

var dest = [];
dest['character'] = {x:8, y:8};

function positionEqual(pos1, pos2) {
        return (pos1.x == pos2.x) && (pos1.y == pos2.y)
}

function update () {
   positionEqual(this.gridEngine.getPosition('character'), dest['character'])
}

```

Thanks again,
T

**Comment by Annoraaq** [comment]
Hi @gureckis,

I think the most straightforward way to achieve this is to create a new observable of positionChangeFinished() by filtering it:

```javascript
const moveToCoordinates = {x: ..., y: ...};
const currentCharId = ...;
...
const moveToFinishedObservable = this.gridEngine
    .positionChangeFinished()
    .pipe(
      filter(({ charId, exitTile, enterTile }) => 
          charId === currentCharId && enterTile.x === moveToCoordinates.x && enterTile.y === moveToCoordinates.y
      )
    )
    .take(1);
```

I did not test that specific code snippet but it should communicate the idea:
For each moveTo you want to react on reaching the target tile you will create a new observable, that fires only when a specific char enters the position you wanted to move to.

However, there are some things to mention about this approach:

1. MoveTo might never lead to the character reaching the target position because it is blocked. In this case you will be waiting forever.
2. If you cancel the movement before reaching the target, you need to manually unsubscribe from your observable because otherwise it might fire on a later movement that reaches the former target tile.

Please let me know if this solution works for you.

It might be a good idea to provide an example and/or a convenient method for the plugin, so you don't need to write that code by yourself in the future.

**Comment by splashsky** [comment]
> It might be a good idea for us to provide an example and/or a convenient method for the plugin, so you don't need to write that code by yourself in the future.

I +1 this idea. Sounds similar to the need I have of an observable that returns the final destination tile; from our discussion in #159

**Comment by gureckis** [comment]
thanks this is very helpful!

**Comment by Annoraaq** [comment]
I created an issue for that feature #171
