### ISSUE TITLE
click events on gridCharacters 

### ISSUE THREAD

**Issue by gureckis** [Annoraaq/grid-engine#168]
I'd like to enable clicking on a character and having something happen.  I can register 'pointerdown' events to the character's sprite but then I can't access information about the grid character itself (e.g., `.getPosition()`)

here's an example which does register the click but I can't access the identity of the character:

```
this.gridEngine.gridCharacters.get('pumpkin0').sprite.on('pointerdown', function(pointer) {
     console.log('clicked on this character, but I only know the identity of the sprite');
});
```

but this doesn't work:

```
this.gridEngine.gridCharacters.get('pumpkin0').on('pointerdown', function(pointer) {
     console.log('clicked on this character, and with I could access the position!', this.getPosition());
});
```

Is there a recommendation or way to pass click events upwards to the character from the character's sprite?

Thanks!

**update**

Something like this works so I guess if I manually ensured there was some "key" associated with the character's sprite that was the same id used by GridEngine then it could work.

```
 this.gridEngine.gridCharacters.get('pumpkin0').sprite.on('pointerdown', function(pointer) {
    console.log('clicked on this character', this.scene.gridEngine.getPosition('pumpkin0'));
});
```

**Comment by Annoraaq** [comment]
Your last solution would be the recommended one. If you want to access data about a character the preferred way is over the public methods of the plugin, providing the character Id.

A sprite is just one aspect of a character along with its position, facing direction etc.

This brings me to another recommendation: don't use the gridCharacters property. In the typescript code it is a private property and it is not part of the documentation. It is intended for internal use only (just like the character objects it holds). Its name and structure might change anytime. So it is best to access a characters properties with the corresponding documented methods.

There is none at the moment for retrieving the sprite. The reason is, that the sprite is created outside of the plugin so it should be easy to keep a reference to it outside grid-engine.

However, it might be a good idea for us to provide a method to get a characters sprite, so you don't need to keep track of the references yourself.

**Comment by Annoraaq** [comment]
I created an issue for this #170

**Comment by gureckis** [comment]
thank you for your help and advice!
