### ISSUE TITLE
`getFacingPosition()` returns `Vector2` instead of `Position`

### ISSUE THREAD

**Issue by bloonguyen1207** [Annoraaq/grid-engine#211]
I'm using the latest version of grid-engine and it seems like `getFacingPosition()` returns `Vector2` instead of `Position`

![image](https://user-images.githubusercontent.com/14237312/143505179-2945fcf4-dc1a-46d3-b0ba-a9c573414035.png)
![image](https://user-images.githubusercontent.com/14237312/143505042-c7802bbc-8292-4474-983f-5710d9cbaa40.png)

**Comment by Annoraaq** [comment]
Hi @bloonguyen1207. You are totally right.
However, that should not be a big problem because a Vector2 does satisfy the Position interface (that means having an x and y property) or expressed another way: Position is a structural subtype of Vector2. But since Vector2 is not a class that should be exposed it would be better to narrow it down to a position before returning it.

Thank you for the hint!

**Comment by Annoraaq** [comment]
fixed with 2.12.0
