### ISSUE TITLE
setting collision between specific characters

### ISSUE THREAD

**Issue by k88885180** [Annoraaq/grid-engine#219]
how can I set up collision between specific player character and npc, or player and objects, so that players cannot walk over it? (See attach for example)
![1639985476938](https://user-images.githubusercontent.com/60676550/146846461-a55e5a2a-d4b7-4c6e-a702-aec2821e2389.gif)
?

**Comment by Annoraaq** [comment]
Hey @k88885180 

collisions with objects can either be achieved by using the tilemap like explained [here](https://annoraaq.github.io/grid-engine/usage/collision.html) **OR** by placing objects as if they were characters. Just use gridEngine.addCharacter() and make sure you set `collides` to true in the character config.

Characters are colliding with each other automatically if they have the `collides` flag enabled in their configs.

**Comment by k88885180** [comment]
Thanks so much for the quick response! On the same subject, is there a way to only set collision to specific groups of characters? As in, have players not collide with npcs, but both groups collide with objects (for example, players can walk past npcs, but neither can walk past trees).

**Comment by Annoraaq** [comment]
While there are no collision layers yet, there is a feature that is called [character layers](https://annoraaq.github.io/grid-engine/features/character-layers.html). 

While I think collision groups are a cool feature for the roadmap (in fact I just added this #220), you can achieve this with a workaround:
You could have one character layer for players and one for npcs. Then npcs would collide with each other and players with each other but not players with npcs. However, one problem with that approach is, that you can place only one of those groups (players or npcs) on the character layer connected to the tilemap layer.

For example let's say you have a character layer **ground** with a tilemap layer containing some ground tiles like rocks and trees that should collide with players and npcs. Then you can either place npcs or players on that **ground** layer. If you want both groups to collide with the ground tiles but not with each other, you could place an invisible tile layer called [collision layer](https://annoraaq.github.io/grid-engine/usage/collision-layers.html) with the same tiles colliding as the **ground** layer. However, this is not optimal since you have to keep both layers in sync.

**Comment by k88885180** [comment]
I see, thank you for the suggestion, I'll try this for now. Looking forward to this feature in the future!!

**Comment by Annoraaq** [comment]
Hey @k88885180, I think I will start working on it now. There are more people asking for it so I think it should be the most important thing. I think it should be finished soon 👍

**Comment by zewa666** [comment]
@k88885180 i just had the same situation today where I wanted friendly NPCs to be able to walk through the player and the new collision group feature makes this easily doable https://annoraaq.github.io/grid-engine/examples/collision-groups.html

**Comment by Annoraaq** [comment]
I will close this issue because it is solved with collision groups in 2.13.0.
