### ISSUE TITLE
Simplify tests

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#222]

**Comment by zewa666** [comment]
could you elaborate whats on your mind with this issue?

**Comment by Annoraaq** [comment]
This is only for simplification of the unit tests. So while not having any influence on the functionality of the plugin, it will influence the speed of future development.

**Comment by zewa666** [comment]
I understand. My question was more with regards what those kind of simplifications would be. looking at how you structured your jest tests I felt they already look pretty decent.

**Comment by Annoraaq** [comment]
Oh I see. The main thing would be to get away from the intensive use of stubs. Of course they have their place and should not be abandoned at all but the style in the unit test so far has been to stub anything besides the class under test.

That lead to some problems and I wanted to replace the stubs in many places where they only stub classes that also belong to GridEngine.

There are different opinions about that out there. Here are some nice resources about that in case you are interested:

https://martinfowler.com/articles/mocksArentStubs.html
https://www.thoughtworks.com/insights/blog/mockists-are-dead-long-live-classicists

**Comment by zewa666** [comment]
yep thats what I've assumed you were after. looking at e.g the GridEngine tests there is a bunch of stubbing + mocked modules going on. the lack of an IoC container for sure promotes the use of stubs vs manually crafted class fakes.

if its solely due to LOC used for mocking/stubbing you could perhaps go down jests automock route where every import/dep gets as the name suggests automatically mocked.

anyways, let me just say the level of coverage and test dedication you already have is super refreshing to see.

**Comment by Annoraaq** [comment]
LoC was not the main thing I had in mind. I think that many tests in the case of this plugin would actually profit from the more integrative testing that would follow from replacing the stubs not only by fakes but by the real implementation. For example the tight interaction between GridTilemap and GridCharacter would profit from that. Using only stubs binds the test strongly to the concrete implementation. I just felt that every time I made small changes I had to touch so many tests... But yes, LoC is also an issue. Both the code and especially the test files are too long. So that should be improved as well. But one at a time 😅 

> anyways, let me just say the level of coverage and test dedication you already have is super refreshing to see.

Thanks :) I try to stick to TDD as much as I can.

**Comment by zewa666** [comment]
having written the test for the steppedOn feature I kind of start to get the feeling what you're saying. Having to mock an observable with a Subject vs simply calling moveTo and letting the actual positionChangeFinished fire is a bit tedious.

An integration test feels hard to create whereas an E2E test might actually be easier. So my thoughts for my specific test would be:
* create a demo game (like your docs samples)
* start up a dev server per test via jest
* start an E2E test with Puppeteer or Playwright
* expose gridEngine via window global
* do the test logic
* assert result via gridEngine getters

wdyt?

**Comment by Annoraaq** [comment]
I think having some central e2e tests can be quite useful. I thought about E2E tests for some important activities like those in the examples.

I see E2E tests as something to have additionally to the unit tests.

So what I was thinking when opening this issue was to simply reduce the mocking/stubbing to external components. So as an example: to make the unit test that you wrote more simple and robust against implementation changes we could not mock the GridCharacter (like it was done in basically all the unit tests in the code base) but use a real instance only mocking external stuff like Phaser sprites. Then we don't need to mock the positionChangeFinished() observable.

But this is not always easy. One thing a have thought about (but not thought through yet) is writing something that is comparable to a test harness for a character. You might know test harnesses for UI components (in Angular for example). These abstract the interaction with UI objects for the test. If we had such an abstraction for say GridCharacter, then it might be much easier to trigger and check certain behavior of it in surrounding tests.

**Comment by zewa666** [comment]
I'm not 100% sure I follow your idea of the test harness (guess you meant Material Components Harness). If I understand properly it's merely a test adapter/shim which delegates UI interactions to it's host. So in your example the GridCharacterHarness would do exactly what? Use a GridEngine Mock as Host and delegate/rewrite direct interactions (Move, Stop, Animate ...) to the GridEngine? Perhaps I'm also struggling to see the point as typically a harness isn't written for your own library to use (well that happens over time) but primarily for consumers of your libraries components so that they can improve their own apps tests stability. So e.g. myself, if I'd ever to go and unit test my own game :rofl: 

What I see as the fundamental part of the gridEngine's dependency is the `update` hook. So since you brought up Angular, as far as I see, offering a convenience wrapper like `fakeAsync` to create a scoped phaser-zone (handling sprite mocks etc.) and a `tick` helper to simulate game loop progression (time, delta) could create the necessary environment to run integration tests on a full GridEngine instance.

```ts
it('should move character to position', fakePhaser(() => {
  const grid = new GridEngine(mockedPhaserScene);
  let arrived = false;

  grid.moveTo(...)
  grid.steppedOn(...).subscribe( () => arrived = true)

  tick(10);

  expect(arrived).toBeTrue();
}));
```

But then again, I don't know your code-base nor Phaser good enough to really form a proper opinion. And it seems you've already put quite some thinking into this topic so I'll be looking forward to see what you'll come up with. Keep up the good work :+1:

**Comment by Annoraaq** [comment]
No worries. I did not understand it 100% either 😄 

I have to think about it and play around with some code to see whether it is really feasible or a dead end.

You are right, I meant Material Component Harnesses. They are actually based on the [page object](https://martinfowler.com/bliki/PageObject.html) pattern. It means that you encapsulate the behavior of the UI in the harness (the page object) in order to abstract interactions from the implementation details. For example if you would like to select an item of a `<select>` element, you can use something like `harness.selectItem(...)`. This abstracts from the concrete implementation of the `<select>` component.
The reason is that you often need to write boilerplate code like `document.querySelector('select.some-class option');` and then trigger a click event or whatever. And then the CSS class names change or not a native `<select>` is used anymore and you have to change all your tests. I hope you see the point.

However, it is work to create and maintain such a harness and therefore you might not want to write one for each component in your application. But I think it has value even for components that are not exposed by your library. Say you have a component that is used in 20 other components in your app. You could either stub it away or you leave it and change 20 tests every time you change something in your component.

But back to topic: I could't say how such an abstraction for the GridCharacter might look like exactly, yet. It is just a rough idea. So for now it is not an option.


The phaser-zone sounds like an interesting idea... 🤔  It could make things easier for integrative testing.

**Comment by Annoraaq** [comment]
Some tests are already simplified. There is no need anymore to track this in an issue, as this is an ongoing thing.
