### ISSUE TITLE
How to truely remove a character from the scene with grid engine

### ISSUE THREAD

**Issue by evan-boissonnot** [Annoraaq/grid-engine#225]
Hi

When I use : 
`this.gridEngine.removeCharacter(id)`, it is not remove the character from the scene.

I mean after calling this method, I can yet see the character in the tilemap.

How can I properly remove a character ?

**Comment by Annoraaq** [comment]
Hi @evan-boissonnot,

by calling `removeCharacter(id)` you are removing it from the GridEngine. What remains on the screen is the sprite. You can remove it like any sprite in phaser (for example by calling `destroy()` on it like [http://labs.phaser.io/view.html?src=src%5Cinput%5Cgame%20object%5Cdestroy%20sprite%20on%20down%20event.js](here)).

GridEngine does not handle the destruction of the sprite because it also did not create it, so it could very well be that you want to remove the character from GridEngine but keep the sprite in some situations.

**Comment by evan-boissonnot** [comment]
Hi, 

OK, many thanks. I have tried and everything is ok ! 

By the way : it's a really great job your grid engine, I like it so much !
