### ISSUE TITLE
moveTo return promise/obs to indicate done

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#239]
i have often in my game the need to perform either an emote or changing the facing direction after a finished move. E.g I can order an NPC to start gathering resources at XY and once he arrives there he/she confirms the action.

i have a helper like this

```ts
private async waitForCurrentMovementStopped() {
    return firstValueFrom(this.scene
      .gridEngine
      .movementStopped()
      .pipe(
        filter(m => m.charId === this.id),
        take(1)
      ));
  }
```

and wondered whether moveTo could return either a promise (preferably) or obs so that can be handled in one go?

**Comment by Annoraaq** [comment]
`moveTo()` already returns an observable: https://annoraaq.github.io/grid-engine/api/methods.html#moveto
It should do just what you need.

**Comment by zewa666** [comment]
hmm I could swear I checked the return type of the function and it said void. Will double check it later. thx for the hint

**Comment by zewa666** [comment]
I'm sorry it seems my vscode project had some troubles. after a wipe of npm_modules and re-installing I can see the intellisense suggestions now properly and the returned obs.

**Comment by zewa666** [comment]
hey @Annoraaq, I've just realized it's not exactly the same as my `waitForCurrentMovementStopped` example above. The observable fires way too soon even though the movement is not yet finished.

**Comment by Annoraaq** [comment]
Hey @zewa666.

You are right, the observable emits when the movement starts. It is like `positionChangeStarted()` in that sense.

I am not sure whether it would be a good idea to change that because in case you need it to emit on `positionChangeStarted`, you could not get that anymore.

Or to put it another way: it is easy to change the observable to wait for `movementStopped`. But if it emits when the movement has finished, you can't make it fire earlier anymore, if you know what I mean. So I think it is more flexible the way it is right now.

But you should be able to easily modify the observable to do what you want:

```javascript
this.gridEngine.moveTo('player', ...).pipe(
  switchMap(() => this.gridEngine.movementStopped().pipe(
      rxjs.filter(({ charId }) => charId == 'player')
  ))).subscribe(...);
```

**Comment by zewa666** [comment]
exaclty what I wanted to propose with the config override. The description of the method gave me the wrong impression

> . It will return an observable that will fire whenever the moveTo movement is finished or aborted

so it sounded somewhat as after done. but to male things easier, keeping the current behavior and adding a config option would be definitely helpful as it saves a couple of operator imports and LOC

**Comment by Annoraaq** [comment]
I created an issue for that #241
