### ISSUE TITLE
Moving to a random location

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#269]
Hey there,

I'm kind of finishing my building-construction part of the game and have an interesting challenge. Take a look at the picture below.
![move-to-free-space](https://user-images.githubusercontent.com/2861414/162617434-9c90959b-c35f-436d-ba17-bcdd078eaec6.png)

So while a construction site is in state `not-built`, all the tiles have their `properties.ge_collide` set to `false`. Once I start construction though (interacting with the sign to the lower left) the building goes into state `under-construction`, which sets `ge_collide` to `true`.

Now I'd like the Player character to automatically move off the blocked tiles to any free surrounding tiles (highlighted with the red lines). The point is though that those surrounding tiles might be blocked by another NPC or whatever, so I can't pin-point it to one specific tile for every building.

I thought this might make an interesting addition to [moveTo](https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#moveTo), where targetPos instead of being a `Position`, could become an `Position[]` and the Grid Engine picks a random free spot of these, while respecting the `MoveToConfig` settings, if not accessible tries the next one and so on and so forth

**Comment by Annoraaq** [comment]
Interesting case.

What you could do right now as workarounds:

1. Use [NoPathFoundStrategy CLOSEST_REACHABLE](https://annoraaq.github.io/grid-engine/typedoc/enums/NoPathFoundStrategy.html#CLOSEST_REACHABLE). But if the tiles of the building are not yet blocked it might lead your char to a point still inside the building.

2. Use [NoPathFoundStrategy STOP](https://annoraaq.github.io/grid-engine/typedoc/enums/NoPathFoundStrategy.html#STOP) and check the [result of moveTo](https://annoraaq.github.io/grid-engine/typedoc/enums/MoveToResult.html) until you find an unblocked path. But this is not optimal since it needs a cycle in the game loop to run.

To solve this problem more elegant in the future I see a couple of options:

1. #216 deals with a similar problem. By allowing to specify which positions are allowed for the pathfinding algorithm and which are not, you could solve your problem by just forbidding the tiles of your building and use CLOSEST_REACHABLE for your desired position.

2. Expose pathfinding. If you could check if there is a path to a destination before starting to move a char, you could implement your suggested solution and more. You could for example decide whether you want to pick a different target randomly from a pool of possible target positions like you suggested, or whether you want to have a specific order/priority of target positions.

3. Provide a new NoPathFoundStrategy that allows giving alternative targets. This is less flexible than option 2 but more comfortable.


In the end I think we should implement all three solutions because they all have their strengths.
Probably option 2 is the most flexible one and also the least effort which is why I would prioritize this.

But 1 and 3 are also important and should be on the roadmap.

**Comment by zewa666** [comment]
well my naive approach would be to take all the surrounding tiles that are free (no NPC and no blocking object on them) and than Math.random select one and pass to moveTo. the proposed NOPath Stop would be the cherry on top. So that somewhat sounds like option 2.

Option 3 sounds like what I had kind of in mind originally

Option 1 is actually a quite interesting approach as I could describe blocked/not allowed tiles, which is easy given I already have the grid available.

So funny enough all the 3 approaches would work, I cant even say which one "feels" best. But I agree that 2 sounds like the one with most control.

**Comment by Annoraaq** [comment]
I will close this issue. Method 1 and 2 are implemented and 3 will follow. There already exists an issue for it: #271
