### ISSUE TITLE
Animated tiles

### ISSUE THREAD

**Issue by Raiper34** [Annoraaq/grid-engine#313]
Hi, is it possible to add animated tiles? I have multiple object types in my game with animations (flame, doors, and teleports). I wonder if it is possible or not. Thanks for the answer.

**Comment by Annoraaq** [comment]
Hey, it should be no problem. It depends a bit on how you implement them because to my knowledge there is no out-of-the-box support in phaser tilemaps for that.
If you simply change the tile of the tilemap in regular intervals that should not be a problem.

You could also add animated sprites. Just be careful then with the z-index.

**Comment by Annoraaq** [comment]
Hey, it should be no problem. It depends a bit on how you implement them because to my knowledge there is no out-of-the-box support in phaser tilemaps for that.
If you simply change the tile of the tilemap in regular intervals that should not be a problem.

You could also add animated sprites. Just be careful then with the z-index.

**Comment by Raiper34** [comment]
I implemented it using this approach https://medium.com/@junhongwang/tiled-generated-map-with-phaser-3-d2c16ffe75b6 
Thanks for your awesome Grid engine, it is really a piece of diamond :)

**Comment by Annoraaq** [comment]
Glad to hear it worked and that you like GridEngine! 👍
