### ISSUE TITLE
Importing breaks ems vs common; cannot find correct import for some methods

### ISSUE THREAD

**Issue by Distortedlogic** [Annoraaq/grid-engine#315]
Importing breaks ems vs common -

So in GridEngine package.json main is set to esm.min.js and this was breaking my app. I kept getting `SyntaxError: Unexpected token 'export'`

I am using NextJS react framework on the frontend with typescript. It seems after compilation the dev server expects the GridEgine package to be in commonJS, hence the error since `export` is an esm thing and not a commonjs thing.

I changed the package,json main to plain min.js in GridEgine in my node_modules and this fixed the error. This is my first time running into this error with any package I have used. I do not think my work around is a good long term solution. TBH I do not know what a good long term solution would look like. Maybe there is something I can set in the tsconfig to have it not use esm.min.js? Any thought, ideas, or already known knowledge would be appreciated here.

cannot find correct import for some methods -

in the TS declaration file `grid-engine/dist/Direction/Direction` there is supposedly a function called `oppositeDirection`. but I cannot figure out how to import it.

Directly importing ei `import {oppositeDirection} from "grid-engine/dist/Direction/Direction"` does work cause the file is just types, but it is the recommended import by TS. Not sure whats going on here? I cant import directly from grid-engine either :/

**Comment by Distortedlogic** [comment]
Seems my work around doesnt completely resolve. After getting a bit further along, now I am getting `V is not a function
TypeError: V is not a function at eval (webpack-internal:///./node_modules/grid-engine/dist/GridEngine.min.js:4:3371)`

**Comment by Distortedlogic** [comment]
I found the culprit for importing from grid-engine. Nextjs uses SSR which doesnt play well with grid-engine when import is performed server side. Using Nextjs dynamic importing, components using grid-engine are not rendered server side, which completely resolves.

I am still left with the other issue of how do i import methods like oppositeDirection?

**Comment by Annoraaq** [comment]
Hey @Distortedlogic, so regarding your question about `oppositeDirection`. It is a method that is used internally by GridEngine and therefore not exported. Only the Direction enum from that file is exported, because it is needed to pass directions to exposed methods of GridEngine.

Generally I try to only make as few as possible methods part of the public interface of GridEngine. The reason for that is that once I expose it, I need to keep it backwards compatible and can't simply change or refactor it.

However, if there is a high demand for some internal functionality it might be worth to make it part of the public API. So at the moment it is not part of it. If there is a strong wish to use it we could make it possible.

-------------------------

Regarding your other question:

Currently GridEngine comes as ESM or as iife. There is no commonJs, because it is usually not used on the backend side with node, but in the browser with Phaser.js. However, we can't currently use UMD because esbuild does not support that.

I never checked it with node to be honest. But it would be good to make it also work on node. Worst case would be to also ship a cjs version.

**Comment by Annoraaq** [comment]
I am on the side working on a headless version of GridEngine that should run in node independent of Phaser. The idea is to allow a headless server version that smoothly communicates with the client version (still using phaser). But this is still in a very early stage. So no guarantee that this is going to come. But I will have to solve that node issue for this anyway. I will keep you up to date.

**Comment by Annoraaq** [comment]
I guess, you could resolve the issue? I am closing this. Let me know if it persists.
