### ISSUE TITLE
Can be used turnTowards animation? additionally "setTexture" and "many steps" problems

### ISSUE THREAD

**Issue by Sinanaltundag** [Annoraaq/grid-engine#333]
1- When call turnTowards function one after another, becauseof no promise, only last facingDirection can be seen on screen. can we add a turning animation?

2- And can I ask (I ask this at discussions but i think this can be a bug) 
I use isometric game example so custom walking, and when I change spriteSheet with setTexture, only one frame can be seen. when start walking, character turn back old texture because of custom walking animation function use old texture. I try to run again
```
createPlayerAnimation.call(this, "up-right", 26, 29, "new-texture"); // I configure func for detect "new-texture"
...
```
but nothing changed. Is there anyway to change texture? ( I success when use customWalkingAnimationMap with only use setTexture function, but it uses only one frame for a tile and on isometric map it is not useful)

3- last question; I want to set a function "move 2 or many tiles on same direction". 
when I try to moveTo function and if there is a collide on direction, character goes around collide but I want only straight movement.
when I try to move function with for loop, it does not work because of promise, is there anyway to move many steps

thanks for suggestions

**Comment by Annoraaq** [comment]
# Question 1

So when you want to use the built-in animations of GridEngine, then there is no turning animation. It will simply change to the "standing" frame of the corresponding direction. However, you can deactivate built-in animations by just **not** passing [walkingAnimationMapping](https://annoraaq.github.io/grid-engine/typedoc/interfaces/CharacterData.html#walkingAnimationMapping). You are free to use whatever animations you like with plain Phaser then. There is a basic example [here](https://annoraaq.github.io/grid-engine/examples/custom-walking-animation.html). You might find the [directionChanged](https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#directionChanged) observable handy.

# Question 2

That sounds to me like a pure Phaser issue and the Phaser community might be better suited to answer it. If I understand you correctly, you are trying to change a texture of a sprite, after the animation has been created. And then it is not picked up by the animation? Maybe you could create 2 sprites here instead of changing the texture and then create 2 animations. You can then exchange the sprite along with the animation. Just an idea, though. I am not sure about the best practice here.

# Question 3
There are a couple of settings for pathfinding that you can use for `moveTo`.  You could set [noPathFoundStrategy](https://annoraaq.github.io/grid-engine/typedoc/interfaces/MoveToConfig.html#noPathFoundStrategy) to [CLOSEST_REACHABLE](https://annoraaq.github.io/grid-engine/typedoc/enums/NoPathFoundStrategy.html#CLOSEST_REACHABLE). And additionally you can restrict the pathfinding by passing a function that only allows straight paths: https://annoraaq.github.io/grid-engine/typedoc/interfaces/MoveToConfig.html#isPositionAllowedFn

There is an example for restricting pathfinding here: https://annoraaq.github.io/grid-engine/examples/pathfinding-restriction.html

**Comment by Sinanaltundag** [comment]
Thanks for this detailed answers.
For second question as you are right, I mean that may be a Phaser bug, but I do not know phaser details so ask here if any simple method in grid engine for solution and as you say I try to use 2 sprites

I will try all suggestions and turn back if success or not

**Comment by Sinanaltundag** [comment]
Your suggestion about straight move is success but I want to say a problem about "CLOSEST_REACHABLE"
I could not understand reason. 
1- if target tile have collide "player" not move normally (i think)
2- if target is out of map "player" not move normally (i think)
3- if target tile has no collide and there is one tile has collide on path, "player move to collide on path and stop normally  (i think)
4- but may be it occurs when two or more collide, "player" do not move even if target tile has no collide
Because of this my Player moves a little randomly and problem for me
I use this code sample for move straight both ortogonal and isometric map and result is same

```
 const position = this.gridEngine.getPosition("player");
this.gridEngine.moveTo(
              "player",
              { x: position.x, y: position.y + 5 }, 
              {
                noPathFoundStrategy: "CLOSEST_REACHABLE",
                isPositionAllowedFn: (pos) => {
                  return pos.x === position.x;
                }
              }
            );
```
for example at this position "player" not move from y:5 to y:6 when target y:9
![screenshot](https://user-images.githubusercontent.com/87491141/204037490-aac4f990-6dc2-4a99-a5f6-57f6aacf2704.png)

Have you any suggestion for me?

**Comment by Annoraaq** [comment]
I think it might be because of a bug that I recently discovered while trying to expose the pathfinding. There is a bug in the pathfinding algorithm implementation in combination with CLOSEST_REACHABLE. I will provide a fix soon. I created a bug, so you can track it (#336)

**Comment by Sinanaltundag** [comment]
I try to setSprite about Question2 for your suggestion but I could not success
I load at preload func alternative sprite sheet like "player2"
then on event 
```
          const playerSprite2 = this.add.sprite(0, 0, "player2");
          this.gridEngine.setSprite("player", playerSprite2);
```
but this add a new sprite, my character not change. It is possible I use wrong so
is there any example for change sprite

**Comment by Annoraaq** [comment]
Can you provide more context? Just replacing the sprite works fine for me:
https://codesandbox.io/s/tender-wildflower-u7p6cc?file=/src/index.js

In that example, walk somewhere and press space. Then the sprite should be exchanged with one that has a different scaling so you can distinguish them.

**Comment by Sinanaltundag** [comment]
thanks for sample code, I found my error reason that when I use "container" setSprite not working 

> Can you provide more context? Just replacing the sprite works fine for me: https://codesandbox.io/s/tender-wildflower-u7p6cc?file=/src/index.js
> 
> In that example, walk somewhere and press space. Then the sprite should be exchanged with one that has a different scaling so you can distinguish them.

**Comment by Annoraaq** [comment]
I see. Providing a sprite and a container only makes sense if you want to use the build-in animation. Then the sprite is used for animation but the container has precedence for positioning.

I think we should be more specific about this in the docs. I added a todo.
