### ISSUE TITLE
Increase documentation and examples

### ISSUE THREAD

**Issue by Senzo13** [Annoraaq/grid-engine#381]
Hi, I think it would be interesting to add to the documentation these points: 

* How to update gridEngineConfig containing the characters to add one more, for example in an online game context when a player logs in (personally I haven't found a really viable solution yet even if I search in the github)

* Even if it's quite simple to find in your github it might be really good to explain how to modify the speed of a character in the documentation and I would add for example different use cases to for example allow a sprite to riding a horse when a key is pressed, and for example allow it to run, because even if it's not very complicated it might be really good to show how you would do it

* Add examples of use with Tiled Map (screen or video) to demonstrate the use of layers with layers in the documentation

* Show an architecture for using Grid Engine Phaser, and Colyseus or Socket.io to create an online game base (could allow creators and users to create quality content)

**Comment by Annoraaq** [comment]
Hey, not sure if that is what you mean by documentation, but did you check out the [API documentation](https://annoraaq.github.io/grid-engine/api/), too?

It should cover your first two points with: [addCharacter](https://annoraaq.github.io/grid-engine/api/classes/GridEngine.html#addCharacter) and [setSpeed](https://annoraaq.github.io/grid-engine/api/classes/GridEngine.html#setSpeed).

Generally you can find all the available methods there and they also have at least a short description about what they do.

The examples are to demonstrate in code how to solve more complex use cases that sometimes involve more than one method.

There are also some tutorials that cover certain things. There are several that cover using Tiled:
https://annoraaq.github.io/grid-engine/p/collisions/
https://annoraaq.github.io/grid-engine/p/character-layers/

The last point is interesting. While I have never used Colyseus, I can't say anything about that. But networking is a really complex topic that demands certain tradeoffs, so that I personally don't have a recommended way or a best practice for using it with GridEngine, yet.
I think it also depends a bit on the specific use case (which tradeoffs are best for your game). That does of course not mean that such a best practice does not exist. So if someone has a good proposal, it would be great to have it in the docs.

**Comment by Senzo13** [comment]
Very interesting, I had obviously badly searched in the API, I thought when I looked at it that it only included the examples of the documentation.

For Socket.io I myself am creating my own project with your library and phaser, I'm getting close to a result, but it's not that simple indeed, but I'm close to a convincing result and viable, if I ever manage to refine it to make it really usable easily I will make sure to create a healthier architecture and offer it to you. For now I still face many obstacles since I'm new to Grid-Engine and I'm still quite new to Phaser

**Comment by Annoraaq** [comment]
> I had obviously badly searched in the API

I think if you could not find it, others will have problems, too. For me it is really hard to judge because I know exactly where to look. So I am a bad test subject 😄 

If you have any idea how to make it easier to find, let me know.

Also, let me know if you have a working architecture you would like to share. I think there is a large demand for it.

**Comment by Annoraaq** [comment]
You can also join our discord server: https://discord.gg/C4jNEZJECs

**Comment by dzoba** [comment]
Thank you very much for your work on this project.  As a newcomer I wanted to share my experience:

I have found it difficult to get the examples running locally.  As best I can tell they are hidden in a folder called "x" a couple levels deep inside docs/static.  I tried using the `serve` npm package to serve those folders but they do not load in the browser.

I also tried using `npm run serve` and it does load an example, but, I want to see the others.

What I would really like is a top level examples directory that has a minimally running app (eg create-react-app) that I can just run and load on my system, for each example.

**Comment by Annoraaq** [comment]
Good idea. 

> As best I can tell they are hidden in a folder called "x" a couple levels deep inside docs/static.

That is for the static site generator that creates the docs. Maybe they can be copied there as part of the build process. That would allow to have them in some other directory.

I created an own issue for this: #383 

Also, there is an example repo for typescript which basically implements one of the examples. So if you just need a point to start, that might be interesting: https://github.com/Annoraaq/grid-engine-ts-example

**Comment by Annoraaq** [comment]
@Senzo13, @dzoba, can I close this one? 
In other words: would #383 already fix this? If so, I would close this one to avoid duplicates.
