### ISSUE TITLE
`GridEngineHeadless.isTileBlocked` returns wrong block state with layer name

### ISSUE THREAD

**Issue by io-q** [Annoraaq/grid-engine#422]
As following defined tilemap, GridEngineHeadless.isTileBlocked({x: 2, y: 0}, 'someLayer') reutrns true
In my thought, it should return false because {x:2, y:0} is un-blocked in *someLayer*
And there is no character layers defined in the tilemap. Dose parameter `layer` work? please help me out, thanks.

```
// Using GridEngine v2.32.4
const tilemap = new ArrayTilemap({
  someLayer: {
    data: [
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...
    ],
  },
  anotherLayer: {
    data: [
      [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
      ....
    ],
  },
});
```

**Comment by Annoraaq** [comment]
You need to specify the layers as being character layers by setting isCharLayer: true

https://annoraaq.github.io/grid-engine/api/interfaces/ArrayTilemapInputLayer.html#isCharLayer

If not, they are considered as normal tile layers. I got confused by this myself yesterday. Maybe the default should be true🤔

**Comment by io-q** [comment]
Thanks @Annoraaq for your quick response
I tried a layer with `isCharLayer`. But the result is not my expected. Do you mean,  a layer with `isChraLayer` will not be regarded as a normal tile then grid engine will treat its tile as tile-blocked?
I made a quick test to compare `GridEngineHeadless.isTileBlocked` with `Tile.isBlocking`, could you have time to review it?  thanks
https://codesandbox.io/s/vigorous-snowflake-t6sd8z?file=/src/index.js

**Comment by Annoraaq** [comment]
Ok so I checked it and there are two problem, which is probably why you got confused:

1. There is a bug in the ArrayTilemap implementation, which means that charLayers are not really detected as some (event with the `isCharLayer` property set to `true`.

2. To achieve what you want, you need to specify all layers as charLayers

A tile layer **can** be a char layer but it does not have to. In your code `tilemap.getTileAt(1, 0, "someLayer").isBlocking` is checking the blocking properties of tile layers of the tilemap.

If you use GridEngine to check for collisions, it uses only char layers.

I can explain what happens in your example. You create a tilemap with 3 tile layers: `someLayer`, `anotherLayer` and `charLayer`. `charLayer` is not only a tile layer but also a char layer.

If you call `grid.isTileBlocked(
  { x: 1, y: 0 },
  "someLayer"
)`, Grid Engine will check position (1,0) on char layer `someLayer`. However, there does not exist a char layer `someLayer`. It returns true because a position on a non-existing layer is considered to be blocked.

If you do not specify a char layer (which is only possible because Grid Engine used to have no char layers), Grid Engine will   consider all tile layers to be backwards compatible.

In case you have not seen it, there is a tutorial about char layers here: https://annoraaq.github.io/grid-engine/p/character-layers/

**Comment by Annoraaq** [comment]
So, I just released v2.33.2. It should be fixed by now. If you now use `isCharLayer: true` it should work as expected. Let me know if it works.

Sorry for the confusion.

**Comment by io-q** [comment]
Awesome, expected usages work with v2.33.2, thanks for your quick move and patient declare. I mis-understood the collision policy between char layer and tile layer. 
BTW your design is so great especially the headless part. So deno runtime can easily import game-engine just set “type” as "module" in package.json. Just let you know

**Comment by Annoraaq** [comment]
Thanks for the hint! I have just released a new version with `type: "module"`.
