### ISSUE TITLE
Rotating the player sprite does not seem to care for it's rotation origin

### ISSUE THREAD

**Issue by iUltimateLP** [Annoraaq/grid-engine#423]
Hey, great library! 

I've noticed strange behaviour when trying to call `setRotate` on a sprite that's used as a player. Given this simple example scene:
```ts
create() {
        // Create the map and tileset
        this.map = this.make.tilemap({key: "tilemap"});
        this.tileset = this.map.addTilesetImage("tileset_city", "tileset")!;
        
        // Instantiate each layer
        for (var layerIdx = 0; layerIdx < this.map.layers.length; layerIdx++) {
            var tiledLayer : Phaser.Tilemaps.LayerData = this.map.layers[layerIdx];
            const layer : Phaser.Tilemaps.TilemapLayer | null = this.map.createLayer(tiledLayer.name, this.tileset, 0, 0);
            
            if (layer) {
                layer.scale = SCENE_SCALE;
            }
        };

        this.player = this.add.sprite(0, 0, "player");
        this.player.setDisplaySize(TILE_SIZE * SCENE_SCALE, TILE_SIZE * SCENE_SCALE);
        this.player.setOrigin(0.5, 0.5);
        this.player.setRotation(deg2rad(0));

        // Set up the grid engine configiguration
        const gridEngineConfig : GridEngineConfig = {
            characters: [
                {
                    id: "player",
                    sprite: this.player,
                    startPosition: { x: 30, y: 30 },
                    facingDirection: Direction.RIGHT,
                }
            ],
            numberOfDirections: 4
        }

        // Create grid engine
        this.gridEngine.create(
            this.map,
            gridEngineConfig,
        );
}

update(time: number, delta: number): void {
        this.rotation = (this.rotation + (delta * 0.25)) % 360;
        this.player?.setRotation(deg2rad(this.rotation));
}
```

Without gridengine, the above scene produces the following (correct) example of where the sprite rotates around it's center: 
![gridengine1](https://github.com/Annoraaq/grid-engine/assets/8491339/18c350fd-d8d3-446c-9fcd-7c0a69873bc3)

But with gridengine, the origin of the sprite is always set at 0,0 as it seems, not allowing me to rotate the sprite around it's center:
![gridengine2](https://github.com/Annoraaq/grid-engine/assets/8491339/e0ce62b6-81d7-4184-96b8-1adbc97ebfb2)

Perhaps I'm misunderstanding something, or it's a bug. In any case, thanks for the library!

**Comment by iUltimateLP** [comment]
Update: it seems that calling `setOrigin(0.5)` on the sprite in `update()` serves as a workaround, although that might not be optimal!

**Comment by Annoraaq** [comment]
Hey @iUltimateLP, happy to hear you like Grid Engine.

I know why your problem happens, but I am not sure about the best way to solve it.

Grid Engine sets the origin to (0,0). It needs to know the origin in order to place the sprite correctly to the center of the tile. I think it would not be a problem to change the origin to something else, but then someone who wants to have an origin of (0,0) has the same problem you experience now.

The first solutions coming to my mind would be:

1. Grid Engine could store the original origin and only set their own one for repositioning the sprite and then set the old origin afterwards again (basically what you are doing as a workaround right now). The fact that your workaround works, is an indicator that this solution should work.

2. Let Grid Engine detect the origin and calculate the positioning of the sprite in relation to the origin.

I tend to favor option 1 over 2, because 2 is probably more complex.

I am also open for more ideas.
