### ISSUE TITLE
Using Characters With Different Sprite Sizes Causing Incorrect Render

### ISSUE THREAD

**Issue by shanelarson** [Annoraaq/grid-engine#432]
First: Thanks for the amazing plugin. Made getting into this type of game development easy and fast.

Second: The Player and NPC are both 16x32 sprites. The Ham and Wood are both 16x16 sprites. Notice the Player and NPC render correctly and the Player and Ham/Wood do not.

https://github.com/Annoraaq/grid-engine/assets/26246673/96979e2c-6e44-449d-b602-fce162fe6dec

**Comment by shanelarson** [comment]
I had the Player and NPC inside a Container. I did not have the Ham and Wood inside a Container. Once I put the Ham and Wood inside a Container it rendered correctly. Is this a bug?

**Comment by Annoraaq** [comment]
The sprite dimensions should not influence the depth sorting (z-index). But I think that is the problem here, right?

Can you share more of your code? It might be a bug, but maybe there is something else in your setup that causes the problem.

Did you pass the container of the player and npc to grid engine via: https://annoraaq.github.io/grid-engine/api/interfaces/CharacterData.html#container ?

If you only passed the sprite which is in a container, it will not position it correctly. The reason for this is that Phaser uses a local depth sorting for all objects within a container. So if you use a container, you have to pass it to Grid Engine.

**Comment by Annoraaq** [comment]
@shanelarson I will close the issue for now. Feel free to reopen if there are any news.
