### ISSUE TITLE
Support 8 directions

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#90]

**Comment by awweather** [comment]
Will you add diagonal support for non-isometric maps as well?

**Comment by Annoraaq** [comment]
Would that be useful to you? I think it will not be too hard when it is already implemented for isometric maps.

**Comment by awweather** [comment]
Yeah, I would like to be able to support omnidirectional movement if it's not too much work.

**Comment by jasonmcleod** [comment]
Just found this today! Would also love to see this feature. I'm anxious to see what you come up! May take a stab at is also, but I see you are working on it as recently as today 🙌

**Comment by Annoraaq** [comment]
It's coming soon! 😁

**Comment by Annoraaq** [comment]
@neu5 @awweather @jasonmcleod 
Version 1.14.0 should now support 8 directions. It was a large change so I hope everything works as expected. Please provide feedback if something is not working as expected or could be improved :) Thank you

**Comment by awweather** [comment]
Hi!  I had some time to play around with the 8 direction movement and wanted to get your thoughts.  Since my game uses click to move, I was hoping that the moveTo method would be able to interpolate which direction to move based on last position.  Since the engine currently knows how to "move diagonally" given an input of two arrow keys, could it also determine how to move diagonally based off a last position/new position?  

I think my other solution would be to use .move instead of .moveTo, and then my movement system can figure out the direction, but I'm struggling a bit to think through how I'll sync that with my server.

**Comment by Annoraaq** [comment]
Hi @awweather,

as implemented at the moment, the moveTo method will get the shortest path from the current position to the target position. If you enabled the 8-direction mode (setting `numberOfDirections` to `8` in the config - https://annoraaq.github.io/grid-engine/api/config.html), it will also take diagonal movements into account.

Isn't that what you need? This example here shows how the moveTo methods works with 8 directions. As you can see, diagonal movement is included: https://annoraaq.github.io/grid-engine/examples/8-directions-move-to.html

**Comment by awweather** [comment]
Whoops, I'm an idiot. I was still referencing an old version of the grid engine.  Everything is working. Thanks!
